### PR TITLE
Navigation bar

### PR DESCRIPTION
**Pull request by tonnymuchui**
- I added A Navigation bar with three sections: Books list, Add book form & Contact info.
- I added click links functionality to navigate to different sections.
- Live link: https://tonnymuchui.github.io/Awesome-books/

### CODE REVIEW

**Review by AmaduKamara — APPROVED** [review]
# Status: APPROVED 🟢🟢🟢 

Hi @tonnymuchui & @Iptysam,

Good job team, your project is complete! 

## Highlights:
✅ You used Gitflow correctly
✅ No linter error
✅ Good descriptive PR
✅ All links and page sections work fine as expected 👍
✅ App is nicely styled 👍  

There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by tonnymuchui** [comment]
Thank you so much. though my dashboard is still  showing REVIEW PENDING

**Comment by AmaduKamara** [comment]
The project is working fine and I already did the review. The linter checks were all working and after I approved, the deployment one is showing an error and I can't approve on your dashboard with a single linter error. Please fix it. I will wait so I can approve it if you can fix it.

**Comment by AmaduKamara** [comment]
Good job on fixing the deployment issue. I can go ahead and approve now. 👍

**Pull request merged**
